-- Migration: create plant_analysis table with user attribution
create table if not exists public.plant_analysis (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  user_id uuid,
  image_url text,
  name text,
  confidence numeric,
  description text,
  tips jsonb,
  constraint fk_user
    foreign key(user_id) references auth.users(id) on delete set null
);

-- Example RLS policies (enable RLS on the table if desired and then configure policies):
-- alter table public.plant_analysis enable row level security;
-- Allow authenticated users to insert rows with their own user_id
-- create policy "Insert own analysis" on public.plant_analysis
--   for insert using (auth.uid() = user_id) with check (auth.uid() = user_id);
